# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20160427_1613'),
        ('reviews', '0002_update_email_length'),
    ]

    operations = [
    ]
